### ISSUE TITLE
Unbound type constructor expression

### ISSUE THREAD

**Issue by andrenth** [janestreet/ppx_metaquot#2]
Hi

I found this library trying to update the jbuild dependencies via opam pin. I understand it's under heavy development, so maybe you're aware of this.
                             
When running `opam pin add .` I get the following build error:

    # Command [5] exited with code 2:
    # $ (cd _build/default && /home/andre/.opam/4.04.0/bin/ocamlc.opt -w -40 -g -bin-annot -I     /home/andre/.opam/4.04.0/lib/ocaml/compiler-libs -I /home/andre/.opam/4.04.0/lib/ppx_core -I    /home/andre/.opam/4.04.0/lib/ppx_traverse_builtins -no-alias-deps -I lifters -o    lifters/ppx_metaquot_lifters.cmo -c -impl lifters/ppx_metaquot_lifters.ml)
    # File "lifters/ppx_metaquot_lifters.ml", line 5, characters 11-21:
    # Error: Unbound type constructor expression

If I'm not mistaken, `expression` comes from `ppx_core`, though I have it pinned to the git HEAD version as of now and it still won't find it.

Thanks,
Andre

**Comment by andrenth** [comment]
I guess I didn't have all other dependencies on git HEAD. I updated all repositories this morning and now I'm able to build ppx_metaquot without errors.

Sorry for the noise.

**Comment by ghost** [comment]
You can also use our development opam repository:

```
$ opam repo add janestreet https://github.com/janestreet/opam-repository.git
```

**Comment by andrenth** [comment]
Nice to know :)

Thanks!
