### ISSUE TITLE
Adding locations to expressions

### ISSUE THREAD

**Issue by jonathan-dilorenzo** [janestreet/ppx_metaquot#3]
Hey,

I'm currently working on migrating from ppx_tools/metaquot to this one since I can't figure out how to get ppx_tools working with jbuilder.

I've run into an issue where this library doesn't seem to support the @metaloc attribute so I was wondering what you use instead or if it would be possible to add support for it?

I.e. if I currently have this:
`[%expr do_some_stuff ] [@metaloc loc]`

which creates an expression node and sets its location to be `loc`, what would I want in ppx_metaquot?

Thanks in advance!

**Comment by hhugo** [comment]
@diml, can you comment on this ?

**Comment by ghost** [comment]
`ppx_metaquot` always the variable `loc` in scope for the location. So `[%expr X] [@metaloc loc]` is the same as `[%expr X]`. To do the same as `[%expr X] [@metaloc blah]`, you would need to write:

```ocaml
let loc = blah in
[%expr X]
```

**Comment by hhugo** [comment]
ppx_metaquot was merged into https://github.com/ocaml-ppx/ppxlib/.
If you have more questions, it should happen there.

**Comment by jonathan-dilorenzo** [comment]
Excellent! Thanks for the response! Looks like my code shouldn't need many changes then.
